config/routes.rb
Rails.application.routes.draw do

  # get 'news/new' => "news#new"
  # post 'news/create' => "news#create"
  # delete 'news/:id/destroy' => "news#destroy"
  resources :news, only: [:new, :create, :destroy]

  resources :my_schedules, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
  resource :favorites, only: [:create, :destroy]
  end
  resources :groups, only: [:index, :new, :create, :show, :edit, :update, :destroy]

  get "join" => "groups#join"
  post "join" => "groups#current_member_join"
  patch "withdrawal" => "groups#withdrawal"

  devise_for :members,skip: [:passwords], controller: {
    registrations: "registrations",
    sessions: 'sessions'
  }
  get 'members/success' => 'members#success'
  get 'members/show' => 'members#show'


  root to: 'homes#top'
  get 'members/schedules', to: 'homes#schedules'
  get 'members/schedule_details', to: 'homes#schedule_details'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord

  has_many :members, dependent: :destroy
  has_many :news, dependent: :destroy
  has_many :my_schedules, through: :members

# グループ作成画面／参加画面のバリデーション
  validates :group_name, presence: true
  validates :group_code, presence: true
  validates :password, presence: true

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :member_logged_in? #メンバーログインしていない場合、不可

  # 新規グループ作成の入力画面を表示
  def new
    @group = Group.new
  end

  # newで入力した値に応じて、新規グループの作成
  def create
    @group = Group.new(group_params)
    ## グループを作成した人は自動的に管理者とする
    @group.admin_member_id = current_member.id
    ## グループが作成できたら、お知らせ共有／お知らせ投稿／スケジュール集計グループでの共有画面へ行く
    if @group.save
      current_member.update(group_id: @group.id)
      redirect_to members_schedules_path, notice: 'グループを作成しました'
    ## グループの作成ができなかった場合、新規グループ作成の入力画面へ行く
    else
      render :new
    end
  end

  # 既存グループに参加する画面の表示
  def join
  end

  # joinで入力した値に応じて、既存グループに参加させる
  def current_member_join
    @group = Group.find_by(group_code: params[:group_code], password: params[:password], deleted: false)

    ## グループが見つかった場合、ログインしているメンバーが、選択したグループに加入し、
    ## お知らせ共有／お知らせ投稿／スケジュール集計グループでの共有画面へ行く
    if @group.present?
       current_member.update(group_id: @group.id)
       redirect_to members_schedules_path, notice: 'グループに参加しました'
    ##グループが見つからなかった場合、既存グループに参加する画面へ行く
    else
      render :join
    end
  end

  #参加しているグループの情報画面を表示する
  def show
    ## 現在参加しているグループの情報を探す
    @group = current_member.group
    ## グループに参加しているメンバーを探す
    @members = Member.where(group_id: current_member.group)
  end


  #グループのパスワードを更新する（グループ管理者のみの機能）
  def update
    #現在参加しているグループの情報を探す
    @group = current_member.group
    @group.update(password: params[:group][:password])
    ##更新した場合、参加しているグループの情報画面へ行く
    redirect_to group_path, notice: 'パスワードを変更しました'
  end

  #グループの退会
  def withdrawal

    ## 退会するメンバーが管理者だった場合
    if current_member.group.admin_member_id == current_member.id
    ### グループのdeleted(グループが消されているかどうか)カラムのステータスをTRUEにし、消したこととする
    ### 他のグループメンバーもgroup_idをカラにし、グループから強制的に退会させる
      current_member.group.update(deleted: true)

      @members = Member.where(group_id: current_member.group).update(group_id: nil)
    end
    ## 退会するメンバーが管理者だった場合の処理が済んだ後
    ### memberが持っていたgroup_idをカラにする
    current_member.update(group_id: nil)

    ### 退会後、グループ作成画面へ行く
    redirect_to members_success_path, alert: 'グループを退会しました'

  end

  private
  def group_params
    params.require(:group).permit(:group_name, :group_code, :password)
  end


  # メンバーログインしていない場合に、トップページへリダイレクトするためのアクション
  def member_logged_in?
    redirect_to root_path if !current_member
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<h1>Groups#edit</h1>
<p>Find me in app/views/groups/edit.html.erb</p>
管理者のみの機能としたい

app/views/groups/index.html.erb
<!--このページは存在しない-->

app/views/groups/join.html.erb
<h2 class="text-center py-5">グループへ参加する</h2>
<%= form_with url: join_path, method: :post do |f| %>
<table class="table">
  <tbody>
    <tr>
      <th><div class="text-center">グループID</div></th>
      <th><%= f.text_field :group_code %></th>
    </tr>
    <tr>
      <th><div class="text-center">グループパスワード</div></th>
      <th><%= f.password_field :password %></th>
    </tr>
  </tbody>
</table>

<div class="row justify-content-center">
<%= f.submit 'グループへ参加する', class:"btn btn-success" %>
<% end %>
</div>

<p class="text-center pt-3">すでにあるgroupへ参加する人は、</br>
groupを作成した人から</br>
IDとパスワードを教えてもらってね</p>

<div class="row justify-content-center">
<%= link_to "戻る",members_success_path, class:"btn btn-primary" %>
</div>

app/views/groups/new.html.erb
<h2 class="text-center py-5">新規グループ作成</h2>
<div class="row justify-content-center">
<% if @group.errors.any? %>
  <%= @group.errors.count %>件のエラーが発生しました
  <ul>
    <% @group.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</div>


<div class="row justify-content-center">
<%= form_with model: @group, url: groups_path, method: :post do |f| %>
<p>グループ名</p>
<%= f.text_field :group_name %>
<p>グループID</p>
<%= f.text_field :group_code %>
<p>グループパスワード</p>
<%= f.password_field :password %>

<%= f.submit '新規グループを作成する', class:"btn btn-success ml-5" %>
<% end %>
</div>
<div class="row justify-content-center">
<%= link_to "戻る",members_success_path, class:"btn btn-primary mt-5" %>
</div>

app/views/groups/show.html.erb
<h2 class="text-center py-3">グループ情報</h2>

<table class="table">
  <tbody>
    <tr>
      <th class="table-active"><div class="text-center">グループ名</div></th>
      <th><%= @group.group_name %></th>
    </tr>
    <tr>
      <th class="table-active"><div class="text-center">グループID</div></th>
      <th><%= @group.group_code %></th>
    </tr>
    <tr>
      <th class="table-active"><div class="text-center">グループメンバー</div></th>
      <th>
        <% @members.each do |member| %>
        <%= member.name %>/
        <% end %>
      </th>
    </tr>
    <tr>
      <th class="table-active"><div class="text-center">グループ退会</div></th>
      <th><%= link_to "グループを退会する", withdrawal_path, method: :patch, class:"btn btn-danger", data: {confirm: "本当に退会しますか？"} %></th>
    </tr>

    <!--グループのadminのみの機能-->
    <!--グループメンバーが退会した時などに使用-->
    <% if current_member.group.admin_member_id == current_member.id %>
    <tr>
      <th class="table-active"><div class="text-center">グループ参加パスワード変更</div></th>
      <th>
        <%= form_with model: @group, url:group_path, method: :patch do |f| %>
        <%= f.password_field :password, id: "pass" %>
        <input type="checkbox" onChange="document.getElementById('pass').type = (this.checked) ? 'text' : 'password';">
        パスワードを表示する</br>
        <%= f.submit "パスワードを変更する", class:"btn btn-success mt-3" %>
        <% end %>
      </th>
    </tr>
    <% end %>

  </tbody>
</table>