config/routes.rb
Rails.application.routes.draw do

  # get 'news/new' => "news#new"
  # post 'news/create' => "news#create"
  # delete 'news/:id/destroy' => "news#destroy"
  resources :news, only: [:new, :create, :destroy]

  resources :my_schedules, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
  resource :favorites, only: [:create, :destroy]
  end
  resources :groups, only: [:index, :new, :create, :show, :edit, :update, :destroy]

  get "join" => "groups#join"
  post "join" => "groups#current_member_join"
  patch "withdrawal" => "groups#withdrawal"

  devise_for :members,skip: [:passwords], controller: {
    registrations: "registrations",
    sessions: 'sessions'
  }
  get 'members/success' => 'members#success'
  get 'members/show' => 'members#show'


  root to: 'homes#top'
  get 'members/schedules', to: 'homes#schedules'
  get 'members/schedule_details', to: 'homes#schedule_details'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :correct_user
  before_action :set_group, only: [:schedules, :schedule_details]

  # メンバーサインアップ／ログイン前のトップページ
  def top
  end

  # お知らせ共有／お知らせ投稿／スケジュール集計グループでの共有画面
  def schedules
    ##お知らせ一覧表示（５件表示後は次のページへ・ページネーション）
    ###最新投稿は一番上に来るようにする
    @news_all = @group.news.order("created_at DESC").page(params[:page]).per(5)
    ##お知らせ投稿機能
    ###お知らせのcreateはnewsコントローラーへ記載
    @news = current_member.news.build
    ##グループのスケジュール（月毎集計）表示
    @my_schedules = @group.my_schedules
  end




  #スケジュール詳細画面(１日のグループメンバーのスケジュールを共有）
  def schedule_details
    ##スケジュールカレンダーから直接日付を取得する。
    @day_params = params[:format]
    ## 同じグループに所属する人のスケジュールを取得する
    @my_schedules = @group.my_schedules
  end

  private

  #メンバーログインしており、かつ、グループidを持っているかどうかの確認用アクション
  def correct_user
    if current_member&.group_id.present?
    ##もし、グループidを持っていなかった場合は、メンバーサインイン／ログイン後の画面へ移動する
    elsif current_member
      redirect_to members_success_path
    end
  end

  def news_params
    params.require(:news).permit(:title, :message)
  end

  private

  #現在ログイン中のメンバーが所属するグループのみ表示
  def set_group
    @group = current_member.group
  end



end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/schedule_details.html.erb
<h2 class="text-center pt-3"><%= @day_params %>のスケジュール一覧</h2>
<div class="row justify-content-center">
<%= link_to "みんなの予定に戻る", members_schedules_path, class:"btn btn-info mt-3" %>
</div>
　<table class="table table-bordered">
     <tr class="table-dark">
         <td>日付</td>
         <td>メンバー名</td>
         <td>朝食</td>
         <td>昼食</td>
         <td>夕食</td>
         <td>コメント</td>
         <td>確認OK？</td>
     </tr>

     <tbody>
     <% my_schedules = @my_schedules.search_schedule(@day_params) %>
     <!--< my_schedules = @my_schedules.search_schedule(Time.current.to_date) %>-->
     <% my_schedules.each do |my_schedule| %>


         <tr>
             <td><%= my_schedule.start_date %></td>
             <td><%= my_schedule.member.name %></td>
             <td><% if my_schedule.morning_select %>
                 <!--trueの場合-->
                 必要
                 <% else %>
                 <!--falseの場合-->
                 不要
                 <% end %>
             </td>
             <td><% if my_schedule.lunch_select %>
                 <!--trueの場合-->
                 必要
                 <% else %>
                 <!--falseの場合-->
                 不要
                 <% end %>
             </td>
             <td><% if my_schedule.dinner_select %>
                 <!--trueの場合-->
                 必要
                 <% else %>
                 <!--falseの場合-->
                  不要
                 <% end %>
              </td>
             <td><%= my_schedule.supplement %></td>
             <td>
                 <% if my_schedule.favorited_by?(current_member) %>
                 <p>
                 <%= link_to my_schedule_favorites_path(my_schedule.id), method: :delete do %>
                 ♥<%= my_schedule.favorites.count %> OK
                 <% end %>
                 </p>
                 <% else %>
                 <p>
                 <%= link_to my_schedule_favorites_path(my_schedule.id), method: :post do %>
                 ♡<%= my_schedule.favorites.count %> OK
                 <% end %>
                 </p>
                 <% end %>
                 </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/homes/schedules.html.erb
<h2 class="text-center py-3">みんなの予定</h2>


<!--お知らせの投稿があった場合に表示する-->
<% if @news_all.present? %>
<h4 class="text-center my-3">★みんなのお知らせ★</h4>


<table class="table table-dark">
  <tr>
    <td>投稿者</td>
    <td>タイトル</td>
    <td>メッセージ</td>
    <td>投稿日</td>
    <td></td>
  </tr>
  <tbody>
 <% @news_all.each do |news| %>
      <tr>
      <td><%= news.member.name %></td>
      <td><%= news.title %></td>
      <td><%= news.message %></td>
      <td><%= news.created_at.strftime('%Y/%m/%d %H:%M') %></td>
      <!--投稿した本人の場合のみ投稿削除可能-->
      <td><% if news.member == current_member %>
          <%= link_to "投稿を削除する", news_path(news.id), method: :delete, data: {confirm: "本当に消してよろしいですか？"}, class:"btn btn-dark" %></td>
          <% end %>
 <% end %>
 <%= paginate @news_all %>
  </tbody>
</table>
<% end %>


<div class="container px-5 px-sm-0">
<div class="row">


<div class="col-md-3">

<h4 class="mt-5">★お知らせを投稿★</h4>
<% if @news.errors.any? %>
  <%= @news.errors.count %>
  件のエラーが発生しました
  <ul>
    <% @news.errors.full_messages.each do |message| %>
      <li>
        <%= message %>
        </li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @news, url: news_index_path do |f| %>
<p>タイトル</p>
<%= f.text_field :title %>
<p>メッセージ</p>
<%= f.text_area :message %>
<%= f.submit 'お知らせを投稿', class:"btn btn-success my-2" %>
<% end %>

</div>


<div class="col-md-8 offset-md-1">

<h4 class="mt-5">★みんなの予定★</h4>
<p>朝食・昼食・夕食　それぞれの必要人数が表示されます</p>
<%= link_to "予定を登録する", my_schedules_path, class:"btn btn-primary my-2" %>

<%= month_calendar do |date| %>
  <%= date.day %>
  <% my_schedules = @my_schedules&.search_schedule(date) %>

    <% morning_select = @my_schedules.where(start_date: date, morning_select: true) %>
    <% lunch_select = @my_schedules.where(start_date: date, lunch_select: true) %>
    <% dinner_select = @my_schedules.where(start_date: date, dinner_select: true) %>


    <% if morning_select.present? %>
      <p>朝食:<%= morning_select.size %>名</p>
    <% end %>
    <% if lunch_select.present?  %>
      <p>昼食:<%= lunch_select.size %>名</p>
    <% end %>
    <% if dinner_select.present?  %>
      <p>夕食:<%= dinner_select.size %>名</p>
    <% end %>
    <% if morning_select.present? ||  lunch_select.present? || dinner_select.present? %>
　　  <%= link_to "詳細", members_schedule_details_path(date), class:"btn btn-info" %>
　　<% end %>
<% end %>

</div>
</div>
</div>

app/views/homes/top.html.erb
<h1 class="text-center">GOHAN DOSURUへようこそ</h1>
<p  class="text-center">
  本サイトは、日々のご飯の予定を</br>
登録したgroupのメンバーと一緒に</br>
共有できるアプリです。</br>
まずはメンバー登録をしましょう！</p>

<div class="row justify-content-center">
<%= link_to 'メンバー登録をする', new_member_registration_path, class:"btn btn-success" %>
</div>
<div class="row justify-content-center pt-3">
<%= link_to 'メンバー登録がお済みの方はこちら', new_member_session_path, class:"btn btn-outline-primary" %>
</div>
<div class="row justify-content-center">
<%= image_tag "gohandosuru_cat.png", width: "20%"  %>
</div>