config/routes.rb
Rails.application.routes.draw do

  # get 'news/new' => "news#new"
  # post 'news/create' => "news#create"
  # delete 'news/:id/destroy' => "news#destroy"
  resources :news, only: [:new, :create, :destroy]

  resources :my_schedules, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
  resource :favorites, only: [:create, :destroy]
  end
  resources :groups, only: [:index, :new, :create, :show, :edit, :update, :destroy]

  get "join" => "groups#join"
  post "join" => "groups#current_member_join"
  patch "withdrawal" => "groups#withdrawal"

  devise_for :members,skip: [:passwords], controller: {
    registrations: "registrations",
    sessions: 'sessions'
  }
  get 'members/success' => 'members#success'
  get 'members/show' => 'members#show'


  root to: 'homes#top'
  get 'members/schedules', to: 'homes#schedules'
  get 'members/schedule_details', to: 'homes#schedule_details'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GohanDosuru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!--simple_calendarを読み込むには下記も読み込む必要があるため、追記-->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="sticky-top"> <!--ヘッダーを画面上部へ固定-->
      <nav class="navbar navbar-expand-lg navbar-dark bg-warning"> <!--navバーの作成-->
        <!--アプリケーションのiconを表示-->
        <%= image_tag "gohandosuru_icon.png", width: "5%" %>
        <!--アプリケーション名を表示-->
          <%= link_to "GOHAN DOSURU?", root_path,class: "navbar-brand" %>
        <!--ハンバーガーメニューの作成-->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
      <!--メンバーサインイン後のヘッダー-->
        <% if member_signed_in? %>
          <% if current_member.group_id %>
            <li class="nav-item active">
              <%= link_to "グループ情報を見る", group_path(current_member.group_id), class: "nav-link" %>
            </li>
          <% end %>
        <li class="nav-item active">
          <%= link_to "マイページ", members_show_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "マイスケジュール", my_schedules_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "みんなの予定", members_schedules_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "ログアウト", destroy_member_session_path, method: :delete, class: "nav-link" %>
        </li>

        <% else %>
        <!--メンバーログアウト後のヘッダー-->
        <li class="nav-item active">
         <%= link_to "メンバーログイン", new_member_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "新規メンバー登録", new_member_registration_path, class: "nav-link" %>
        </li>
        <% end %>
        </ul>
      </div>
　    </nav>
    </header>



    <main class="bg-white text-muted">
    <!--フラッシュメッセージの実装-->
    <% if flash[:notice] %>
     <p class="alert alert-success"><%= notice %></p>
    <% elsif flash[:alert] %>
     <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
    </main>
    <footer class="bg-dark text-white mt-5 pt-5 pb-4">
      <!--アプリのロゴ画像-->
      <div class="row justify-content-center">
      <%= image_tag "gohandosuru_logo.png", width: "20%"  %>
      </div>
    </footer>
  </body>
</html>