config/routes.rb
Rails.application.routes.draw do

  # get 'news/new' => "news#new"
  # post 'news/create' => "news#create"
  # delete 'news/:id/destroy' => "news#destroy"
  resources :news, only: [:new, :create, :destroy]

  resources :my_schedules, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
  resource :favorites, only: [:create, :destroy]
  end
  resources :groups, only: [:index, :new, :create, :show, :edit, :update, :destroy]

  get "join" => "groups#join"
  post "join" => "groups#current_member_join"
  patch "withdrawal" => "groups#withdrawal"

  devise_for :members,skip: [:passwords], controller: {
    registrations: "registrations",
    sessions: 'sessions'
  }
  get 'members/success' => 'members#success'
  get 'members/show' => 'members#show'


  root to: 'homes#top'
  get 'members/schedules', to: 'homes#schedules'
  get 'members/schedule_details', to: 'homes#schedule_details'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :group, optional: true
  has_many :my_schedules, dependent: :destroy
  has_many :news, dependent: :destroy
  has_many :favorites, dependent: :destroy




end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  #メンバー情報詳細画を表示
  def show
    @member = current_member
    @group = @member.group
  end

  # メンバーサインイン／ログイン後の画面を表示
  def success
    ## もし管理者がグループを持っていた場合はメンバーサインイン／ログイン後の画面には行かず、
    ## お知らせ共有／お知らせ投稿／スケジュール集計グループでの共有画面へ行く
    if current_member.group&.admin_member_id == current_member.id
      redirect_to members_schedules_path

    ## もしメンバーがグループに所属（グループIDを所持）していれば、メンバーサインイン／ログイン後の画面には行かず、
    ## お知らせ共有／お知らせ投稿／スケジュール集計グループでの共有画面へ行く
    elsif current_member.group_id != nil
      redirect_to members_schedules_path
    end
  end




end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/show.html.erb
<!--自分のmember登録情報を確認、編集するページ-->

<h2 class="text-center py-3">マイページ</h2>

<table class="table">
  <tbody>
  <tr>
    <th class="table-active"><div class="text-center">あなたの名前</div></th>
    <th><%= current_member.name %></th>
    <th></th>
  </tr>
  <tr>
    <th class="table-active"><div class="text-center">所属グループ</div></th>
    <th>
      <!--グループに所属している時のみ表示-->
      <% if member_signed_in? %>
          <% if current_member.group_id %>
      　　　<p class="text-left"><%= @group.group_name %></p>
      　　<% else %>
      　　<p>未所属</p><%= link_to "グループに所属する",members_success_path, class:"btn btn-primary" %>
          <% end %>
      <% end %>
    </th>
    <th></th>
  </tr>
  <tr>
    <th class="table-active"><div class="text-center">メールアドレス</div></th>
    <th><%= current_member.email %></th>
    <th></th>
  </tr>
  <tr>
    <th class="table-active"><div class="text-center">メンバー退会フォーム</div></th>
    <th>
      <% if member_signed_in? %>
         <% if current_member.group_id %>
          <%= link_to "メンバーを退会する場合は、まず、グループを退会してください。",group_path(current_member.group_id) %>
         <% else %>
          <%= link_to "メンバーを退会する", member_registration_path, method: :delete, data: {confirm: "本当に退会してよろしいですか？"}, class: "btn btn-danger"  %></th>
         <% end %>
      <% end %>
    <th></th>
  </tr>
  </tbody>
</table>

app/views/members/success.erb
<h2 class="text-center pt-3">★メンバーログイン中★</h2>
<h4 class="text-center py-5">グループには参加しますか？</h4>
<p class="text-center">グループに参加すると、グループに参加しているメンバーと</br>
   スケジュールの共有ができます。</p>

<div class="row justify-content-center">
<%= link_to '新規グループを作成する', new_group_path, class:"btn btn-primary mb-3" %>
<!--どのように参加するか要検討-->
<%= link_to 'すでにあるグループへ参加する', join_path, class:"btn btn-success ml-3 mb-3 " %>
<!--currentmemberのページにいくようにしたい-->
<%= link_to 'マイページへ行く', members_show_path, class:"btn btn-info ml-3 mb-3" %>
</div>